const posts = [
	{
		id: '1',
		title: 'Post 1',
		body: 'A Version 4 UUID is a universally unique identifier that is generated using random numbers. The Version 4 UUIDs produced by this site were generated using a secure random number generator.',
	},
	{
		id: '2',
		title: 'Post 2',
		body: 'A Version 1 UUID is a universally unique identifier that is generated using a timestamp and the MAC address of the computer on which it was generated.',
	},
	{
		id: '3',
		title: 'Post 3',
		body: 'The UUIDs generated by this site are provided AS IS without warranty of any kind, not even the warranty that the generated UUIDs are actually unique. You are responsible for using the UUIDs and assume any risk inherent to using them. ',
	},
	{
		id: '4',
		title: 'Post 4',
		body: 'The UUIDs generated by this site conform to RFC 4122 whenever possible.',
	},
]

module.exports = posts
